package ssg

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
)

var styleTagRe = regexp.MustCompile(`(?is)<style\b([^>]*)>(.*?)</style>`)

func extractInlineStyleTags(html []byte) (out []byte, extracted []string) {
	// Fast path.
	if !bytes.Contains(bytes.ToLower(html), []byte("<style")) {
		return html, nil
	}

	ms := styleTagRe.FindAllSubmatchIndex(html, -1)
	if len(ms) == 0 {
		return html, nil
	}

	// Build output without the style blocks we extract.
	var buf bytes.Buffer
	buf.Grow(len(html))

	cursor := 0
	for _, m := range ms {
		// m = [fullStart fullEnd attrsStart attrsEnd bodyStart bodyEnd]
		if len(m) < 6 {
			continue
		}
		fullStart, fullEnd := m[0], m[1]
		attrsStart, attrsEnd := m[2], m[3]
		bodyStart, bodyEnd := m[4], m[5]

		if fullStart < cursor {
			continue
		}

		attrs := ""
		if attrsStart >= 0 && attrsEnd >= 0 && attrsEnd <= len(html) {
			attrs = string(html[attrsStart:attrsEnd])
		}

		// Allow opting out of extraction per-tag.
		attrsLower := strings.ToLower(attrs)
		if strings.Contains(attrsLower, "data-ssg-keep") || strings.Contains(attrsLower, "data-ssg-inline") {
			continue
		}

		css := ""
		if bodyStart >= 0 && bodyEnd >= 0 && bodyEnd <= len(html) {
			css = strings.TrimSpace(string(html[bodyStart:bodyEnd]))
		}
		if css == "" {
			// Remove empty style tags too.
			buf.Write(html[cursor:fullStart])
			cursor = fullEnd
			continue
		}

		extracted = append(extracted, css)
		buf.Write(html[cursor:fullStart])
		// Keep line structure somewhat stable.
		buf.WriteByte('\n')
		cursor = fullEnd
	}

	buf.Write(html[cursor:])
	return buf.Bytes(), extracted
}

func injectStylesheetLink(html []byte, href string) []byte {
	href = strings.TrimSpace(href)
	if href == "" {
		return html
	}

	lower := bytes.ToLower(html)
	// Avoid double-injection.
	if bytes.Contains(lower, []byte(`data-ssg="inline-styles"`)) {
		return html
	}

	linkTag := []byte(`<link rel="stylesheet" data-ssg="inline-styles" href="` + href + `" />\n`)

	// Insert before </head> when possible.
	if i := bytes.Index(lower, []byte("</head>")); i >= 0 {
		var out bytes.Buffer
		out.Grow(len(html) + len(linkTag) + 16)
		out.Write(html[:i])
		out.Write(linkTag)
		out.Write(html[i:])
		return out.Bytes()
	}

	// Otherwise insert right after <head ...>.
	if i := bytes.Index(lower, []byte("<head")); i >= 0 {
		j := bytes.IndexByte(lower[i:], '>')
		if j >= 0 {
			j = i + j + 1
			var out bytes.Buffer
			out.Grow(len(html) + len(linkTag) + 16)
			out.Write(html[:j])
			out.WriteByte('\n')
			out.Write(linkTag)
			out.Write(html[j:])
			return out.Bytes()
		}
	}

	// Fallback: prepend.
	return append(linkTag, html...)
}

type inlineStyleAccumulator struct {
	outRel string

	mu     sync.Mutex
	byPage map[int][]styleBlock
	seen   map[string]struct{}
}

type styleBlock struct {
	pageRel string
	css     string
}

func newInlineStyleAccumulator(outRel string) *inlineStyleAccumulator {
	outRel = strings.TrimSpace(outRel)
	if outRel == "" {
		outRel = "css/inline.css"
	}
	return &inlineStyleAccumulator{
		outRel: outRel,
		byPage: map[int][]styleBlock{},
		seen:   map[string]struct{}{},
	}
}

func (a *inlineStyleAccumulator) Add(order int, pageRel string, css string) {
	css = strings.TrimSpace(css)
	if css == "" {
		return
	}

	h := sha256.Sum256([]byte(css))
	key := hex.EncodeToString(h[:])

	a.mu.Lock()
	defer a.mu.Unlock()
	if _, ok := a.seen[key]; ok {
		return
	}
	a.seen[key] = struct{}{}
	a.byPage[order] = append(a.byPage[order], styleBlock{pageRel: pageRel, css: css})
}

func (a *inlineStyleAccumulator) mergedAbs(outDir string) string {
	outRelOS := filepath.FromSlash(a.outRel)
	return filepath.Clean(filepath.Join(outDir, outRelOS))
}

func (a *inlineStyleAccumulator) PageHref(outDir, outFile string) string {
	abs := a.mergedAbs(outDir)
	fromDir := filepath.Dir(outFile)
	rel, err := filepath.Rel(fromDir, abs)
	if err != nil {
		return filepath.ToSlash(filepath.FromSlash(a.outRel))
	}
	return filepath.ToSlash(rel)
}

func (a *inlineStyleAccumulator) WriteMerged(outDir string) error {
	abs := a.mergedAbs(outDir)
	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		return err
	}

	a.mu.Lock()
	keys := make([]int, 0, len(a.byPage))
	for k := range a.byPage {
		keys = append(keys, k)
	}
	sort.Ints(keys)

	var buf bytes.Buffer
	buf.WriteString("/* ssg: merged inline <style> blocks */\n")
	buf.WriteString("/* generated by -extract-inline-styles */\n\n")
	for _, k := range keys {
		blocks := a.byPage[k]
		for _, b := range blocks {
			if b.pageRel != "" {
				buf.WriteString(fmt.Sprintf("/* from %s */\n", b.pageRel))
			}
			buf.WriteString(b.css)
			buf.WriteString("\n\n")
		}
	}
	a.mu.Unlock()

	// Always write the file when enabled to avoid stale content from previous builds.
	return os.WriteFile(abs, buf.Bytes(), 0o644)
}
